"""OpenPathSampling: A python package to do path sampling simulations

OpenPathSampling (http://github.com/choderalab/openpathsampling) is a
python library to do transition interface sampling.
"""

from setuptools import setup
import sys
import os
import subprocess
import yaml
import pprint

sys.path.insert(0, '.')


def trunc_lines(s):
    print s
    parts = s.split('\n')
    while len(parts[0]) == 0:
        parts = parts[1:]

    while len(parts[-1]) == 0:
        parts = parts[:-1]

    parts = [part for part in parts if len(part) > 0]

    print parts

    return '\n'.join(parts)


# +-----------------------------------------------------------------------------
# | GET GIT VERSION
# +-----------------------------------------------------------------------------

def get_git_version():
    # Return the git revision as a string
    # copied from numpy setup.py
    def _minimal_ext_cmd(cmd):
        # construct minimal environment
        env = {}
        for k in ['SYSTEMROOT', 'PATH']:
            v = os.environ.get(k)
            if v is not None:
                env[k] = v

        # LANGUAGE is used on win32
        env['LANGUAGE'] = 'C'
        env['LANG'] = 'C'
        env['LC_ALL'] = 'C'
        output = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, env=env).communicate()[0]
        return output

    try:
        out = _minimal_ext_cmd(['git', 'rev-parse', 'HEAD'])
        git_revision = out.strip().decode('ascii')
    except OSError:
        git_revision = 'Unknown'

    return git_revision


# +-----------------------------------------------------------------------------
# | WRITE version.py FILE
# +-----------------------------------------------------------------------------

def write_version_py(
    prefs,
    filename='openpathsampling/version.py',
):

    cnt = """
# This file is automatically generated by setup.py
short_version = '%(version)s'
version = '%(version)s'
full_version = '%(full_version)s'
git_revision = '%(git_revision)s'
release = %(isrelease)s

if not release:
    version = full_version
"""

    # Adding the git rev number needs to be done inside write_version_py(),
    # otherwise the import of numpy.version messes up the build under Python 3.
    if os.path.exists('.git'):
        git_version = get_git_version()
    else:
        git_version = 'Unknown'

    full_version = prefs['version']
    if not preferences['released']:
        full_version += '.dev-' + git_version[:7]

    print 'writing version file at %s' % filename

    a = open(filename, 'w')
    try:
        a.write(cnt % {
            'version': prefs['version'],
            'full_version': full_version,
            'git_revision': git_version,
            'isrelease': str(prefs['released'])
        })
    finally:
        a.close()


# +-----------------------------------------------------------------------------
# | CONSTRUCT PARAMETERS FOR setuptools
# +-----------------------------------------------------------------------------

def build_keyword_dictionary(prefs):
    keywords = {}

    for key in [
        'name', 'version', 'license', 'url', 'download_url', 'packages',
        'package_dir', 'platforms', 'description', 'requires',
        'long_description'
    ]:
        if key in prefs:
            keywords[key] = prefs[key]

    keywords['author'] = \
        ', '.join(prefs['authors'][:-1]) + ' and ' + \
        prefs['authors'][-1]

    keywords['author_email'] = \
        ', '.join(prefs['emails'])

    keywords["package_dir"] = \
        {package: '/'.join(package.split('.')) for package in prefs['packages']}

    keywords['long_description'] = \
        trunc_lines(keywords['long_description'])

    output = ""
    first_tab = 40
    second_tab = 60
    for key in sorted(keywords.iterkeys()):
        value = keywords[key]
        output += key.rjust(first_tab) + str(value).rjust(second_tab) + "\n"

    pprint.pprint(keywords)
    # print("%s" % output)

    return keywords

# load settings from setup.py, easier to maintain
with open('setup.yaml') as f:
    yaml_string = '\n'.join(f.readlines())

preferences = yaml.load(yaml_string)
setup_keywords = build_keyword_dictionary(preferences)

write_version_py(preferences)


def main():
    setup(**setup_keywords)
    pass

if __name__ == '__main__':
    main()
