package:
  name: openpathsampling-dev
  version: "0.0.3"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib

test:
  requires:
    - nose
    - nose-timer
    - msmbuilder
    - pyemma
    - jupyter_client
    - ipynbtest

  import:
    - openpathsampling

about:
  home: https://github.com/choderalab/openpathsampling
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: framework for running path sampling MD simulations