package:
  name: openpathsampling-dev
  version: "0.0.3"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib

test:
  requires:
    - nose
    - nose-timer
    - python-coveralls
    - msmbuilder
    - pyemma
    - ipynbtest

  imports:
    - openpathsampling

about:
  home: https://github.com/openpathsampling/openpathsampling
  license: GNU Lesser General Public License v2.1 or later (LGPLv2.1+)
  summary: framework for running path sampling MD simulations
