package:
  name: openpathsampling-dev
  version: "0.9.2"

source:
#  git_url: ../../.git
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - future
    - pandas
    - hdf4 4.2.12
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson

test:
  imports:
    - openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
