package:
  name: openpathsampling-dev
  version: "1.1.0"

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - future
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - future
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson
    - psutil
    - pyemma

test:
  imports:
    - openpathsampling

about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
