
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-98ae2c1'
git_revision = '98ae2c1aae59fc703e28cbe27650450030575d50'
release = False

if not release:
    version = full_version
