
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-dd842b0'
git_revision = 'dd842b0ac8be856fd24b4f8f918f5241aefe2514'
release = False

if not release:
    version = full_version
