
# This file is automatically generated by setup.py
short_version = '0.0.1'
version = '0.0.1'
full_version = '0.0.1.dev-4d9e893'
git_revision = '4d9e893cd76b3ead5abd52ef15eb44e8d7ab3b42'
release = False

if not release:
    version = full_version
