
# This file is automatically generated by setup.py
short_version = '0.0.1'
version = '0.0.1'
full_version = '0.0.1.dev-971dbfd'
git_revision = '971dbfd9feae59bf3982d9ab2d10673aac26ed54'
release = False

if not release:
    version = full_version
