
# This file is automatically generated by setup.py
short_version = '0.0.1'
version = '0.0.1'
full_version = '0.0.1.dev-c8390b0'
git_revision = 'c8390b091f71ad46c56af7ee03afd7443a83f9c0'
release = False

if not release:
    version = full_version
