
# This file is automatically generated by setup.py
short_version = '0.0.1'
version = '0.0.1'
full_version = '0.0.1.dev-1fa19a9'
git_revision = '1fa19a99f617846e92dc98c3085eaa5c3203ff83'
release = False

if not release:
    version = full_version
